apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    # container_name üzerinden erişim
    url: http://solar_prometheus:9100
    access: proxy
    isDefault: true
    editable: false
